---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      imagePullSecrets:
        - name: registry-kit
      volumes:
        - name: env
          secret:
            secretName: ${ENV_SECRET_NAME}
      containers:
        - name: app
          image: ${DOCKER_IMAGE}
          volumeMounts:
            - name: env
              readOnly: true
              mountPath: "/app/.env.js"
              subPath: "env_js"
            - name: env
              readOnly: true
              mountPath: "/app/.env"
              subPath: "env_file"
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: STAGE
              value: ${STAGE}
            - name: VERSION
              value: ${VERSION}
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
spec:
  ports:
    - name: api
      port: 8080
      targetPort: api
  selector:
    app: ${APP_NAME}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APP_NAME}-ingress
spec:
  rules:
  - host: "kit.lskjs.ru"
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: ${APP_NAME}
            port:
              name: api
